import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./custom_component/NavBar";
import HeroSection from "./custom_component/HeroSection/page";
import Intro from "./custom_component/Intro/page";
import Services from "./custom_component/Services/page";
import Footer from "./custom_component/Footer/page";
import TeamSection from "./custom_component/TeamSection/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar/>
        <HeroSection/>
        <Intro/>
        <Services/>
        <TeamSection/>
        <Footer/>
       
        {children}
      </body>
    </html>
  );
}
